CREATE TABLE `SEQUENCE` (
  `SEQ_NAME`  VARCHAR(50)           NOT NULL,
  `SEQ_COUNT` DECIMAL(38,0) DEFAULT     NULL,
  PRIMARY KEY (`SEQ_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;