CREATE TABLE IF NOT EXISTS `dealership`.`USER` (
    `ID`       INT    (255) NOT NULL AUTO_INCREMENT COMMENT '',
    `USERNAME` VARCHAR(10)  NOT NULL                COMMENT '',
    `PASSWORD` VARCHAR(20)  NOT NULL                COMMENT '',
    PRIMARY KEY (`ID`)
) ENGINE='InnoDB' DEFAULT CHARSET='utf8' COLLATE='utf8_bin' COMMENT='';